using System.Diagnostics;
using Voxelscape.Utility.Common.Pact.Diagnostics;

namespace Voxelscape.Common.Procedural.Pact.Noise
{
	/// <summary>
	/// Defines a type used to distort the density values generated by an <see cref="INoise4D"/> instance.
	/// </summary>
	public interface INoiseDistorter4D : INoiseDistorter3D
	{
		/// <summary>
		/// Distorts the density value generated by the specified noise function for the given point.
		/// </summary>
		/// <param name="sourceNoise">The original source of the noise to distort.</param>
		/// <param name="x">X value of the input point.</param>
		/// <param name="y">Y value of the input point.</param>
		/// <param name="z">Z value of the input point.</param>
		/// <param name="w">W value of the input point.</param>
		/// <returns>The distorted density value.</returns>
		double Noise(INoise4D sourceNoise, double x, double y, double z, double w);
	}

	public static class INoiseDistorter4DContracts
	{
		[Conditional(Contracts.Requires.CompilationSymbol)]
		public static void Noise(INoise4D sourceNoise)
		{
			Contracts.Requires.That(sourceNoise != null);
		}
	}
}
